name: Capy Converter

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - run: go test ./...
  build:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Preparing buildx
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx create --use
      - name: Building capy-converter images and push to hub
        run: |
          docker buildx build --tag krol44/capy-converter:latest \
                              --push --platform linux/amd64,linux/arm64 .