name: Capy Converter

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - run: go test ./...
  build:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Preparing buildx
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx create --use
      - name: Building capy-converter images and push to hub
        run: |
          docker buildx build --tag ghcr.io/${{ github.repository_owner }}/capy-converter:latest --push \
                              --platform linux/amd64,linux/arm64 .